[profile.default]
evm_version = "cancun"
ffi = true
fs_permissions = [{access = "read-write", path = ".forge-snapshots/"}]
libs = ["lib"]
out = "out"
solc_version = "0.8.28"
src = "src"

[rpc_endpoints]
unichain = "https://unichain.gateway.tenderly.co"

[fmt]
line_width = 100
multiline_func_header = "params_first"
